### ISSUE TITLE
When saturation decreases, the visual does not update.

### ISSUE THREAD

**Issue by James103** [yeelp/Scaling-Feast#51] opened 2020-05-14 21:20 UTC
**Mod Version**: 1.3.1
**Minecraft Version**: 1.12.2
**Loaded Mods**: (Reproducible with just Scaling Feast) 

**Describe the bug**
When saturation decreases, the visual does not update until the max or current hunger changes, you reload the world, respawn, or change dimensions, or your saturation runs out.

**Steps to Reproduce**
1. Give yourself a bunch of saturation.
2. Sprint. Your saturation will decrease internally, but the visual won't update.
3. Keep sprinting, reload the world, eat, etc. The visual will update.

**Expected behavior**
When saturation decreases, the visual updates to match in real-time.

**Additional context**
I ran 3 laps on the track circuit that I made. It looked like my saturation was at full (100.0) for all up until I pitted at the end of the third lap, at which point it instantly decreased to 0.

**Comment by yeelp** [comment] 2020-05-17 21:16
This seems related to #48, which I was having a hard time reproducing. I have a few theories related to this that I'll try when I get some time to work on this. for now, I can say that using Apple Skin prevents this bug altogether since it syncs saturation to the client.

If this turns out to be related to #48, I'm going to mark this as a duplicate and close it.

**Comment by yeelp** [comment] 2020-05-18 19:08
This is almost certainly a duplicate of #48, but this information has helped me devise a solution. I'm going to close this now.

**Closed by yeelp** 2020-05-18 19:08 UTC
Labels: bug, duplicate
