### ISSUE TITLE
How to make appleskin not recognize applecore?

### ISSUE THREAD

**Issue by Narwhal8** [yeelp/Scaling-Feast#88] opened 2020-09-07 00:02 UTC
Hello. I read in the comment about appleskin compatibilty that you can get the tooltips to show somewhat right by making appleskin not recognize applecore. Can i find out either how to do this myself or can someone tell me how to make the appleskin tooltips look right-ish? Thanks!

**Comment by yeelp** [comment] 2020-09-18 22:33
the problem isn't so much that it's not possible or that there's a de facto way to do it, but that there's a trade off. To see more about what I mean, check #85 - it explains my entire stance on the matter (more or less).

tl;dr AppleSkin's tooltips will never really 'look right' without additional work on AppleSkin's side. Work that I don't think is entirely warranted for the developer to invest time in. At least, this is the conclusion I reached.

I'm going to close this issue since I answered your question. If you have comments or more questions you can still ask them here (Unless it's related to #85, in which case please post you questions or comments there).

**Closed by yeelp** 2020-09-18 22:33 UTC
Labels: question
